- hosts: localhost
  gather_facts: no
  roles:
          - role: aws-webserver
            count: 1
            name: "webserver"

- hosts: tag_Nmae_webserver
  gather_facts: no
  roles:
          - role: config-server
